### ISSUE TITLE
Macros stopped working

### ISSUE THREAD

**Issue by GJsoft** [Rolisteam/DiceDiscordBot#2]
I've found an error in an old macro and wanted to remove it and replace it with a new one. Removal worked fine, but for some reason, it's not anymore possible to add new macros at all, even when using the exact same input used last time. The list stays empty.
I've tested it on multiple servers and test accounts, and the issue is persistent, so I'm suspecting it may be currently global -- better let you know sooner than later.

**Comment by obiwankennedy** [comment]
I made some change on macro to accept space character. It may cause those errors.

Don't hesitate to give me your macro. So I can check if macros work and if your macro works as well.

**Comment by GJsoft** [comment]
For example, just something like "!macro r d20" is not being added to the list. Nothing complex at all.

**Comment by obiwankennedy** [comment]
just add 0 at the end to say 'I'm not using regular expression'. I recall now, it is easier to make the third parameter mandatory to deal with space character.  

I will fix that, if I can or fix the documentation, and add some feedbacks.

**Comment by GJsoft** [comment]
Ah, another parameter makes sense tbh. Works with it flawlessly now. No problem then. If it's in the documentation soon, it'd be perfect. I'll play around a  bit with space implementation and let you know if everything is working like it should!
One more thing: The message you get for having no macros when looking it up with macro list is "No reccorded macro for this server". Small typo, but just letting you know.
Thanks for the incredibly fast response!
